[general]
	timezone="Australia/Sydney"

[1wire]
	host="localhost"
	port=4304
	timeout=5 # seconds, will reconnect after this if no response
	sensor_period=30 # seconds
	switch_period=0.1 # seconds
	debug=true

[mqtt]
	host="localhost"
	port=1883

[database]
	dsn="dbi:SQLite:ha.db"
	user=""
	password=""

[wemo]
	debug=0
	switch_period=1 # seconds
